FROM alpine:3.8

# A couple of packages to debug Docker image.
# You can comment these later when creating the final image.
RUN apk update && apk add ca-certificates emacs
RUN apk add --no-cache curl
